# Railway Deployment Configuration

# Build Command
npm install --prefix backend

# Start Command  
cd backend && npm start

# Root Directory
/

# Environment Variables (Add these in Railway Dashboard)
NODE_ENV=production
PORT=3005
MONGODB_URI=mongodb+srv://your-connection-string
JWT_SECRET=expense-tracker-secret-2024